name: publish

on:
    push:
        branches:
            - master

jobs:
    build-and-test:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v1
            - uses: actions/setup-node@v1
              with:
                  node-version: 10
            - run: npm ci
            - run: npm test

    npm-publish:
        needs: build-and-test
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v1
            - uses: actions/setup-node@v1
              with:
                  node-version: 10
            - run: npm ci
            - run: npm run build
            - name: Semantic Release
              uses: cycjimmy/semantic-release-action@v2
              id: semantic
              with:
                  branch: master
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
                  NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
                  NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

    publish-github-pages:
        needs: npm-publish
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v1
            - uses: actions/setup-node@v1
              with:
                  node-version: 10
            - run: npm ci
            - run: npm run build-storybook
            - name: 'Deploy to GitHub Pages'
              uses: crazy-max/ghaction-github-pages@v1
              with:
                  target_branch: gh-pages
                  build_dir: storybook-static
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
